apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-service
  labels:
    app: time-service
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-service
  template:
    metadata:
      labels:
        app: time-service
        component: backend
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: time-service
          image: time-service
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
              name: grpc
              protocol: TCP
          env:
            - name: LISTEN_ADDRESS
              value: "0.0.0.0:9090"
          args:
            - "--listen=0.0.0.0:9090"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: time-service
  labels:
    app: time-service
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: grpc
  selector:
    app: time-service
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: time-service
  namespace: default
spec:
  parentRefs:
    - name: time-service
      group: ""
      kind: Service
      port: 9090
  rules:
    - matches:
        - method:
            service: smpl.api.time.v1.TimeService
            method: GetCurrentTime
            type: Exact
      backendRefs:
        - kind: Service
          name: time-service
          port: 9090
---
# apiVersion: linkerd.io/v1alpha2
# kind: ServiceProfile
# metadata:
#   name: time-service.default.svc.cluster.local
#   namespace: default
# spec:
#   routes:
#     - name: GetCurrentTime
#       condition:
#         method: POST
#         pathRegex: /smpl\.api.time\.v1\.TimeService/GetCurrentTime
